### ISSUE TITLE
🙉 Problem for the local project to work for me. 

### ISSUE THREAD

**Issue by DianyelaMaldonado** [anuarhdz/craftcms-tailwind#1]
I have an installation problem, my steps were:

1. Git clone.
2. npm install
3. I wanted to access public html for the valet link but I get this: `No such file or directory.`

Am I missing any steps?

I will be very grateful if you can please help me with this issue. 👾

**Comment by anuarhdz** [comment]
Sorry! I forgot to update the readme.
In this setup I use `public` instead of `public_html`.
